<% if ENV['MONGOHQ_URL'] %>
  production:
    sessions:
      default:
        uri: <%= ENV['MONGOHQ_URL'] %>
        options:
          skip_version_check: true
          safe: true
<% else %>
  production:
    sessions:
      default:
        database: short_the_rails_production
        hosts:
        - localhost:27017
        options:
          skip_version_check: true
          safe: true
<% end %>

development:
  sessions:
    default:
      database: short_the_rails_development
      hosts:
        - localhost:27017
      options:



test:
  sessions:
    default:
      database: short_the_rails_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
